# -*- coding: utf-8 -*-
"""Delhi AQI Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10E1PyZIB3ISo0_gYb7g0fAanl0XxjfSV
"""

from google.colab import files
uploaded=files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import warnings
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor
from sklearn import metrics
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.decomposition import PCA
warnings.filterwarnings('ignore')

df=pd.read_csv("delhi_aqi.csv")
df
data1=df.copy()

df.head()

df.describe()

df.shape

df.index

df.columns

df.dtypes

df.nunique()

df.info()

df.isnull().sum().sum()

for i in range(1,6):
  df.plot(kind='scatter',x=df.columns[i],y='pm2_5',color='blue')
  df.plot(kind='scatter',x=df.columns[i],y='pm10',color='green')

for j in range(8,9):
  df.plot(kind='scatter',x=df.columns[j],y='pm2_5',color='blue')
  df.plot(kind='scatter',x=df.columns[j],y='pm10',color='green')

#RANDOM FOREST
X=df.iloc[:,1:2]
Y=df.iloc[:,6:7].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
print("SCATTER PLOT OF NORMAL CO & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=Y_test_PM25,color='green')
plt.xlabel('CO')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,1:2]
Y=df.iloc[:,6:7].values.reshape(-1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
y_pred_PM25=reg.predict(X_test_PM25)
print("ACTUAL DATA")
print(np.mean(Y_test_PM25))
print("PREDICTION")
print(np.mean(y_pred_PM25))
print("\n")
print("SCATTER PLOT OF PREDICTED CO & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=y_pred_PM25,color='green')
plt.xlabel('CO')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,2:3]
Y=df.iloc[:,6:7].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
print("SCATTER PLOT OF NORMAL NO & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=Y_test_PM25,color='green')
plt.xlabel('NO')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,2:3]
Y=df.iloc[:,6:7].values.reshape(-1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
y_pred_PM25=reg.predict(X_test_PM25)
print("ACTUAL DATA")
print(np.mean(Y_test_PM25))
print("PREDICTION")
print(np.mean(y_pred_PM25))
print("\n")
print("SCATTER PLOT OF PREDICTED NO & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=y_pred_PM25,color='green')
plt.xlabel('NO')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,3:4]
Y=df.iloc[:,6:7].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
print("SCATTER PLOT OF NORMAL NO2 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=Y_test_PM25,color='green')
plt.xlabel('NO2')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,3:4]
Y=df.iloc[:,6:7].values.reshape(-1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
y_pred_PM25=reg.predict(X_test_PM25)
print("ACTUAL DATA")
print(np.mean(Y_test_PM25))
print("PREDICTION")
print(np.mean(y_pred_PM25))
print("\n")
print("SCATTER PLOT OF PREDICTED NO2 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=y_pred_PM25,color='green')
plt.xlabel('NO2')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,4:5]
Y=df.iloc[:,6:7].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
print("SCATTER PLOT OF NORMAL O3 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=Y_test_PM25,color='green')
plt.xlabel('O3')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,4:5]
Y=df.iloc[:,6:7].values.reshape(-1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
y_pred_PM25=reg.predict(X_test_PM25)
print("ACTUAL DATA")
print(np.mean(Y_test_PM25))
print("PREDICTION")
print(np.mean(y_pred_PM25))
print("\n")
print("SCATTER PLOT OF PREDICTED O3 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=y_pred_PM25,color='green')
plt.xlabel('O3')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,5:6]
Y=df.iloc[:,6:7].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
print("SCATTER PLOT OF NORMAL SO2 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=Y_test_PM25,color='green')
plt.xlabel('SO2')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,5:6]
Y=df.iloc[:,6:7].values.reshape(-1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
y_pred_PM25=reg.predict(X_test_PM25)
print("ACTUAL DATA")
print(np.mean(Y_test_PM25))
print("PREDICTION")
print(np.mean(y_pred_PM25))
print("\n")
print("SCATTER PLOT OF PREDICTED SO2 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=y_pred_PM25,color='green')
plt.xlabel('SO2')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,8:9]
Y=df.iloc[:,6:7].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
print("SCATTER PLOT OF NORMAL NH3 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=Y_test_PM25,color='green')
plt.xlabel('NH3')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,8:9]
Y=df.iloc[:,6:7].values.reshape(-1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM25,Y_train_PM25)
y_pred_PM25=reg.predict(X_test_PM25)
print("ACTUAL DATA")
print(np.mean(Y_test_PM25))
print("PREDICTION")
print(np.mean(y_pred_PM25))
print("\n")
print("SCATTER PLOT OF PREDICTED NH3 & PM2_5")
ax1=plt.scatter(x=X_test_PM25,y=y_pred_PM25,color='green')
plt.xlabel('NH3')
plt.ylabel('PM2_5')

#RANDOM FOREST
X=df.iloc[:,1:2]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
print("SCATTER PLOT OF NORMAL CO & PM10")
ax1=plt.scatter(x=X_test_PM10,y=Y_test_PM10,color='blue')
plt.xlabel('CO')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,1:2]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
y_pred_PM10=reg.predict(X_test_PM10)
print("ACTUAL DATA")
print(np.mean(Y_test_PM10))
print("PREDICTION")
print(np.mean(y_pred_PM10))
print("\n")
print("SCATTER PLOT OF PREDICTED CO & PM10")
ax1=plt.scatter(x=X_test_PM10,y=y_pred_PM10,color='blue')
plt.xlabel('CO')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,2:3]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
print("SCATTER PLOT OF NORMAL NO & PM10")
ax1=plt.scatter(x=X_test_PM10,y=Y_test_PM10,color='blue')
plt.xlabel('NO')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,2:3]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
y_pred_PM10=reg.predict(X_test_PM10)
print("ACTUAL DATA")
print(np.mean(Y_test_PM10))
print("PREDICTION")
print(np.mean(y_pred_PM10))
print("\n")
print("SCATTER PLOT OF PREDICTED NO & PM10")
ax1=plt.scatter(x=X_test_PM10,y=y_pred_PM10,color='blue')
plt.xlabel('NO')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,3:4]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
print("SCATTER PLOT OF NORMAL NO2 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=Y_test_PM10,color='blue')
plt.xlabel('NO2')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,3:4]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
y_pred_PM10=reg.predict(X_test_PM10)
print("ACTUAL DATA")
print(np.mean(Y_test_PM10))
print("PREDICTION")
print(np.mean(y_pred_PM10))
print("\n")
print("SCATTER PLOT OF PREDICTED NO2 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=y_pred_PM10,color='blue')
plt.xlabel('NO2')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,4:5]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
print("SCATTER PLOT OF NORMAL O3 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=Y_test_PM10,color='blue')
plt.xlabel('O3')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,4:5]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
y_pred_PM10=reg.predict(X_test_PM10)
print("ACTUAL DATA")
print(np.mean(Y_test_PM10))
print("PREDICTION")
print(np.mean(y_pred_PM10))
print("\n")
print("SCATTER PLOT OF PREDICTED O3 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=y_pred_PM10,color='blue')
plt.xlabel('O3')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,5:6]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
print("SCATTER PLOT OF NORMAL SO2 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=Y_test_PM10,color='blue')
plt.xlabel('SO2')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,5:6]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
y_pred_PM10=reg.predict(X_test_PM10)
print("ACTUAL DATA")
print(np.mean(Y_test_PM10))
print("PREDICTION")
print(np.mean(y_pred_PM10))
print("\n")
print("SCATTER PLOT OF PREDICTED SO2 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=y_pred_PM10,color='blue')
plt.xlabel('SO2')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,8:9]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=RandomForestRegressor()
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
print("SCATTER PLOT OF NORMAL NH3 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=Y_test_PM10,color='blue')
plt.xlabel('NH3')
plt.ylabel('PM10')

#RANDOM FOREST
X=df.iloc[:,8:9]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
reg.fit(X_train_PM10,Y_train_PM10)
y_pred_PM10=reg.predict(X_test_PM10)
print("ACTUAL DATA")
print(np.mean(Y_test_PM10))
print("PREDICTION")
print(np.mean(y_pred_PM10))
print("\n")
print("SCATTER PLOT OF PREDICTED NH3 & PM10")
ax1=plt.scatter(x=X_test_PM10,y=y_pred_PM10,color='blue')
plt.xlabel('NH3')
plt.ylabel('PM10')

print("SCATTER PLOT BETWEEN PM2_5 AND DATE")
df['date'] = pd.to_datetime(df['date'])
# Plot
plt.figure(figsize=(10, 5))
plt.plot(df.iloc[:,0:1], df.iloc[:,6:7], marker='o', linestyle='-', color='b')
plt.title('Delhi AQI Trend')
plt.xlabel('Date')
plt.ylabel('AQI')
plt.grid(True)
plt.show()

print("SCATTER PLOT BETWEEN PM10 AND DATE")
df['date'] = pd.to_datetime(df['date'])
# Plot
plt.figure(figsize=(10, 5))
plt.plot(df.iloc[:,0:1], df.iloc[:,7:8], marker='o', linestyle='-', color='b')
plt.title('Delhi AQI Trend')
plt.xlabel('Date')
plt.ylabel('AQI')
plt.grid(True)
plt.show()

#BUILDING PIPELINES OF STANDARD SCALER AND MODEL FOR VARIOUS REGRESSORS

pipeline_lr=Pipeline([("scaler1",StandardScaler()),("lr_classifier",LinearRegression())])

pipeline_dt=Pipeline([("scaler2",StandardScaler()),("dt_classifier",DecisionTreeRegressor())])

pipeline_rf=Pipeline([("scaler3",StandardScaler()),("rf_classifier",RandomForestRegressor())])

pipeline_knn=Pipeline([("scaler4",StandardScaler()),("knn_classifier",KNeighborsRegressor())])

pipeline_xgb=Pipeline([("scaler5",StandardScaler()),("xgb_classifier",XGBRegressor())])

#DICTIONARY OF PIPELINES AND MODEL TYPES FOR EASE OF REFERENCE
pipe_dict={0:"Linear Regression",1:"Decision Tree",2:"Random Forest",3:"KNN",4:"XGBoost"}

#LIST OF ALL THE PIPELINES
pipelines=[pipeline_lr,pipeline_dt,pipeline_rf,pipeline_knn,pipeline_xgb]

#FIT THE PIPELINES FOR PM2_5
for pipe in pipelines:
  pipe.fit(X_train_PM25,Y_train_PM25)
  pipe.fit(X_train_PM10,Y_train_PM10)

#ACCURACY OF MODELS WITH PM2_5
print("ACCURACY OF MODELS WITH PM2_5")

X=df[['co','no','no2','o3','so2','nh3']]
Y=df.iloc[:,6:7].values.reshape(-1,1)
X_train_PM25,X_test_PM25,Y_train_PM25,Y_test_PM25=train_test_split(X,Y,random_state=42,test_size=0.20)
cv_results_rms=[]
cv_results_accuracy=[]
for i,model in enumerate(pipelines):

  model.fit(X_train_PM25,Y_train_PM25)
  y_pred_PM25=model.predict(X_test_PM25)
  cv_results_accuracy.append(1-(np.sqrt(mean_squared_error(Y_test_PM25,y_pred_PM25))/(np.max(Y_test_PM25)-np.min(Y_test_PM25))))

print("MODELS")
print(pipe_dict)
print("ACCURACY")
print(cv_results_accuracy)
print("TEST SET")
print(np.mean(Y_test_PM25))
print("PREDICTED SET")
print(np.mean(y_pred_PM25))

#ACCURACY OF NEURAL NETWORK WITH PM2_5
print("ACCURACY OF NEURAL NETWORK WITH PM2_5")
reg=tf.keras.Sequential([tf.keras.layers.Dense(units=1,input_shape=[X_train_PM25.shape[1]])])
reg.summary()
reg.compile(optimizer='adam',loss='mae')
losses=reg.fit(X_train_PM25,Y_train_PM25,batch_size=256,epochs=10)
y_pred_PM25=reg.predict(X_test_PM25)
print("\n")
print("ACCURACY")
print(1-(np.sqrt(mean_squared_error(Y_test_PM25,y_pred_PM25))/(np.max(Y_test_PM25)-np.min(Y_test_PM25))))
print("TEST SET")
print(np.mean(Y_test_PM25))
print("PREDICTED SET")
print(np.mean(y_pred_PM25))

#ACCURACY OF MODELS WITH PCA FOR PM2_5
print("ACCURACY OF MODELS WITH PCA FOR PM2_5")
pca=PCA(n_components=5)
X_train_PM25=pca.fit_transform(X_train_PM25)
X_test_PM25=pca.fit_transform(X_test_PM25)
cv_results_accuracy_pca=[]
for i,model in enumerate(pipelines):

  model.fit(X_train_PM25,Y_train_PM25)
  y_pred_PM25=model.predict(X_test_PM25)
  cv_results_accuracy_pca.append(1-(np.sqrt(mean_squared_error(Y_test_PM25,y_pred_PM25))/(np.max(Y_test_PM25)-np.min(Y_test_PM25))))

print("MODELS")
print(pipe_dict)
print("ACCURACY")
print(cv_results_accuracy)
print("TEST SET")
print(np.mean(Y_test_PM25))
print("PREDICTED SET")
print(np.mean(y_pred_PM25))

#BAR CHART FOR PM2_5
print("BAR CHART FOR PM2_5")
print("\n")
d={'Model':['Linear Regression','Decision Trees Regressor','Random Forest Regressor','KNeighbors Regressor','XGBRegressor',
            'Linear Regression With PCA','Decision Trees Regressor With PCA','Random Forest Regressor With PCA','KNeighbors Regressor With PCA',
            'XGBRegressor With PCA'],'values':[0.9607072215072718, 0.9553556375088366, 0.9676427370698574, 0.9610966947140652, 0.9673575492278396
                                               ,0.9607072215072718, 0.9553556375088366, 0.9676427370698574, 0.9610966947140652, 0.9673575492278396]}
dfModel=pd.DataFrame(d)
dfModel.plot.bar(x='Model',y='values',ylabel='ACCURACY')

#ACCURACY OF MODELS WITH PM10
print("ACCURACY OF MODELS WITH PM10")
X=df[['co','no','no2','o3','so2','nh3']]
Y=df.iloc[:,7:8].values.reshape(-1)
X_train_PM10,X_test_PM10,Y_train_PM10,Y_test_PM10=train_test_split(X,Y,random_state=42,test_size=0.20)
cv_results_rms=[]
cv_results_accuracy=[]
for i,model in enumerate(pipelines):

  model.fit(X_train_PM10,Y_train_PM10)
  y_pred_PM10=model.predict(X_test_PM10)
  cv_results_accuracy.append(1-(np.sqrt(mean_squared_error(Y_test_PM10,y_pred_PM10))/(np.max(Y_test_PM10)-np.min(Y_test_PM10))))

print("\n")
print("MODELS")
print(pipe_dict)
print("ACCURACY")
print(cv_results_accuracy)
print("TEST SET")
print(np.mean(Y_test_PM10))
print("PREDICTED SET")
print(np.mean(y_pred_PM10))

#ACCURACY OF NEURAL NETWORK WITH PM10
print("ACCURACY OF NEURAL NETWORK WITH PM10")
X=df[['co','no','no2','o3','so2','nh3']]
Y=df.iloc[:,7:8].values.reshape(-1)
reg=tf.keras.Sequential([tf.keras.layers.Dense(units=1,input_shape=[X_train_PM10.shape[1]])])
reg.summary()
reg.compile(optimizer='adam',loss='mae')
losses=reg.fit(X_train_PM10,Y_train_PM10,batch_size=256,epochs=10)
y_pred_PM10=reg.predict(X_test_PM10)
print("\n")
print("ACCURACY")
print(1-(np.sqrt(mean_squared_error(Y_test_PM10,y_pred_PM10))/(np.max(Y_test_PM10)-np.min(Y_test_PM10))))
print("TEST SET")
print(np.mean(Y_test_PM10))
print("PREDICTED SET")
print(np.mean(y_pred_PM10))

#ACCURACY OF MODELS WITH PCA FOR PM10
print("ACCURACY OF MODELS WITH PCA FOR PM10")
X=df[['co','no','no2','o3','so2','nh3']]
Y=df.iloc[:,7:8].values.reshape(-1)
pca=PCA(n_components=5)
X_train_PM10=pca.fit_transform(X_train_PM10)
X_test_PM10=pca.fit_transform(X_test_PM10)
cv_results_accuracy_pca=[]
for i,model in enumerate(pipelines):

  model.fit(X_train_PM10,Y_train_PM10)
  y_pred_PM10=model.predict(X_test_PM10)
  cv_results_accuracy_pca.append(1-(np.sqrt(mean_squared_error(Y_test_PM10,y_pred_PM10))/(np.max(Y_test_PM10)-np.min(Y_test_PM10))))

print("MODELS")
print(pipe_dict)
print("ACCURACY")
print(cv_results_accuracy)
print("TEST SET")
print(np.mean(Y_test_PM10))
print("PREDICTED SET")
print(np.mean(y_pred_PM10))

#BAR CHART FOR PM10
print("BAR CHART FOR PM10")
print("\n")
d={'Model':['Linear Regression','Decision Trees Regressor','Random Forest Regressor','KNeighbors Regressor','XGBRegressor',
            'Linear Regression With PCA','Decision Trees Regressor With PCA','Random Forest Regressor With PCA','KNeighbors Regressor With PCA',
            'XGBRegressor With PCA'],'values':[0.9623239026596964, 0.9542322793984794, 0.9672063281598211, 0.9611807431612849, 0.9662791750124926,0.9623239026596964,
                                               0.9542322793984794, 0.9672063281598211, 0.9611807431612849, 0.9662791750124926]}
dfModel=pd.DataFrame(d)
dfModel.plot.bar(x='Model',y='values',ylabel='ACCURACY')

print("R^2:",metrics.r2_score(Y_test_PM25,y_pred_PM25))
print("ADJUSTED R^2:",1-(1-metrics.r2_score(Y_test_PM25,y_pred_PM25))*(len(Y_test_PM25)-1)/(len(Y_test_PM25)-X_test_PM25.shape[1]-1))
print("MEAN ABSOLUTE ERROR:",metrics.mean_absolute_error(Y_test_PM25,y_pred_PM25))
print("MEAN SQUARED ERROR:",metrics.mean_squared_error(Y_test_PM25,y_pred_PM25))
print("ROOT MEAN SQUARED ERROR:",np.sqrt(metrics.mean_squared_error(Y_test_PM25,y_pred_PM25)))

print("R^2:",metrics.r2_score(Y_test_PM10,y_pred_PM10))
print("ADJUSTED R^2:",1-(1-metrics.r2_score(Y_test_PM10,y_pred_PM10))*(len(Y_test_PM10)-1)/(len(Y_test_PM10)-X_test_PM10.shape[1]-1))
print("MEAN ABSOLUTE ERROR:",metrics.mean_absolute_error(Y_test_PM10,y_pred_PM10))
print("MEAN SQUARED ERROR:",metrics.mean_squared_error(Y_test_PM10,y_pred_PM10))
print("ROOT MEAN SQUARED ERROR:",np.sqrt(metrics.mean_squared_error(Y_test_PM10,y_pred_PM10)))

#HEAT MAP
plt.figure(figsize=(8,5))
sns.heatmap(data1.corr(numeric_only=True),cbar=False,annot=True,fmt="0.1f",cmap='coolwarm',linewidths=0.5)
plt.title("Correlation Between the variables of dataset")
plt.show()

plt.scatter(Y_test_PM25,y_pred_PM25,alpha=0.3)
plt.plot([Y_test_PM25.min(),Y_test_PM25.max()],[Y_test_PM25.min(),Y_test_PM25.max()],'r--')
plt.xlabel("Actual PM2.5")
plt.ylabel("Predicted PM2.5")
plt.title("PM2.5 PREDICTION")
plt.show()

plt.scatter(Y_test_PM10,y_pred_PM10,alpha=0.3)
plt.plot([Y_test_PM10.min(),Y_test_PM10.max()],[Y_test_PM10.min(),Y_test_PM10.max()],'r--')
plt.xlabel("Actual PM10")
plt.ylabel("Predicted PM10")
plt.title("PM10 PREDICTION")
plt.show()